[book]
title = "The Xous Operating System"
authors = ["Sean xobs Cross", "Andrew bunnie Huang", "with Contributions from the Betrusted Community"]

[output.html]
# additional-css = ["ferris.css", "theme/2018-edition.css"]
# additional-js = ["ferris.js"]
git-repository-url = "https://github.com/betrusted-io/xous-book"

[output.html.print]
enable = true
